# SOME DESCRIPTIVE TITLE.
# Copyright (C) YEAR THE PACKAGE'S COPYRIGHT HOLDER
# This file is distributed under the same license as the PACKAGE package.
#
# Translators:
# Alain PORTAL <aportal@univ-montp2.fr>, 2006.
# Audrey Simons <asimons@redhat.com>, 2004-2005.
# Bettina De Monti <bdemonti@redhat.it>, 2001.
# Damien Durand <splinux@fedoraproject.org>, 2006.
# Decroux Fabien <fdecroux@redhat.com>, 2006-2007.
# Jérôme Fenal <jfenal@gmail.com>, 2012.
#   <jfenal@gmail.com>, 2011.
# jfenal <jfenal@gmail.com>, 2011.
# Myriam Malga <mmalga@redhat.com>, 2007.
# Stephane Raimbault <stephane.raimbault@free.fr>, 2004.
# Jiri Dostal <jdostal@redhat.com>, 2018. #zanata
msgid ""
msgstr ""
"Project-Id-Version: Spacewalk\n"
"Report-Msgid-Bugs-To: \n"
"POT-Creation-Date: 2020-04-23 10:15+0200\n"
"PO-Revision-Date: 2018-03-16 10:54+0000\n"
"Last-Translator: Copied by Zanata <copied-by-zanata@zanata.org>\n"
"Language-Team: French <trans-fr@lists.fedoraproject.org>\n"
"Language: fr\n"
"MIME-Version: 1.0\n"
"Content-Type: text/plain; charset=UTF-8\n"
"Content-Transfer-Encoding: 8bit\n"
"Plural-Forms: nplurals=2; plural=(n > 1);\n"
"X-Generator: Zanata 4.6.2\n"

#: ../server/apacheAuth.py:66
#, python-format
msgid "incomplete proxy authentication token: %s"
msgstr "Jeton d'authentification proxy incomplet : %s"

#: ../server/apacheAuth.py:84
#, python-format
msgid "Sent proxy signature %s does not match ours %s."
msgstr "La signature de proxy envoyée %s ne correspond pas à la nôtre : %s."

#: ../server/apacheAuth.py:119
msgid "declined proxy authentication"
msgstr "authentification proxy rejetée"

#: ../server/configFilesHandler.py:129 ../server/handlers/app/packages.py:192
#: ../server/handlers/xmlrpc/registration.py:215
#: ../server/handlers/xmlrpc/registration.py:1168
#: ../server/handlers/xmlrpc/registration.py:1307
#, python-format
msgid ""
"\n"
"                   %s Account has been deactivated on this server.\n"
"                   Please contact your Org administrator for more help."
msgstr ""
"\n"
"                   Le compte %s a été désactivé sur ce serveur.\n"
"                   Veuillez contacter votre administrateur d'organisation "
"pour plus d'assistance."

#: ../server/handlers/applet/applet.py:78
msgid "Your system was not found in the RHN database"
msgstr "Votre système n'a pas été trouvé dans la base de données RHN"

#: ../server/handlers/sat/auth.py:45
msgid "ISS is disabled on this satellite."
msgstr "ISS est désactivé sur ce satellite."

#: ../server/handlers/sat/auth.py:50
#, python-format
msgid "Server \"%s\" is not enabled for ISS."
msgstr "Serveur \"%s\" n'est pas autorisé pour ISS."

#: ../server/handlers/xmlrpc/errata.py:64
#, python-format
msgid "Expected a package name, not: %s"
msgstr "Nom de paquet attendu, pas : %s"

#: ../server/handlers/xmlrpc/errata.py:115
#, python-format
msgid "Expected a package, not: %s"
msgstr "Paquet attendu, pas : %s"

#: ../server/handlers/xmlrpc/proxy.py:65
#, fuzzy, python-format
msgid "Spacewalk Proxy service not enabled for server profile: \"%s\""
msgstr "Service RHN Proxy non activé pour le profil de serveur : \"%s\""

#: ../server/handlers/xmlrpc/proxy.py:85
msgid "Invalid session key"
msgstr "Clé de session invalide"

#: ../server/handlers/xmlrpc/proxy.py:93
msgid "This server ID no longer exists"
msgstr "Cet identifiant de serveur n'existe plus"

#: ../server/handlers/xmlrpc/queue.py:433
#, python-format
msgid "Invalid action value type %s (%s)"
msgstr "Type d'action %s invalide (%s)"

#: ../server/handlers/xmlrpc/queue.py:464
#, python-format
msgid "Action %s does not belong to server %s"
msgstr "L'action %s n'appartient pas au serveur %s"

#: ../server/handlers/xmlrpc/scap.py:104
#, fuzzy
msgid "Invalid system_id/action_id pair."
msgstr "Informations d'identification du système invalides."

#: ../server/handlers/xmlrpc/up2date.py:233
#, python-format
msgid "Invalid value %s (%s)"
msgstr "Valeur %s invalide (%s)"

#: ../server/handlers/xmlrpc/registration.py:194
msgid "Required data missing"
msgstr "Données requises manquantes"

#: ../server/handlers/xmlrpc/registration.py:198
msgid "Required members missing"
msgstr "Membres requis manquantes"

#: ../server/handlers/xmlrpc/registration.py:207
msgid "Attempt to register a system to an invalid username"
msgstr "Essai d'enregistrer un système avec un nom d'utilisateur invalide"

#: ../server/handlers/xmlrpc/registration.py:839
msgid "Invalid system release version requested"
msgstr "Version de système demandée invalide"

#: ../server/handlers/xmlrpc/registration.py:1063
msgid ""
"Unable to find a valid network interface, both ipaddr and ip6addr not found."
msgstr ""

#: ../server/handlers/xmlrpc/registration.py:1115
#, fuzzy
msgid "Red Hat Satellite Welcome Message"
msgstr "Message de bienvenue de Red Hat Network"

#: ../server/handlers/xmlrpc/registration.py:1125
#, fuzzy
msgid "Red Hat Satellite Privacy Statement"
msgstr "Déclaration de respect de la vie privée de Red Hat Network"

#: ../server/handlers/xmlrpc/registration.py:1146
msgid "Expected a dictionary as a product argument"
msgstr "J'attendais un dictionnaire en tant qu'arguement produit"

#: ../server/handlers/xmlrpc/registration.py:1374
#, python-format
msgid "Invalid value '%s' for %s (%s)"
msgstr "Valeur incorrecte '%s' pour %s (%s)"

#: ../server/importlib/userAuth.py:98
msgid "You are not authorized to manage packages in the null org"
msgstr ""
"Vous n'êtes pas autorisé à administrer les paquets de l'organisation null"

#: ../server/importlib/userAuth.py:103
#, python-format
msgid "You are not allowed to manage packages in the %s org"
msgstr ""
"Vous n'êtes pas autorisé à administrer les paquets de l'organisation %s"

#: ../server/importlib/userAuth.py:121
msgid "You are not allowed to perform administrative tasks"
msgstr "Vous n'êtes pas autorisé à réaliser des tâches d'administration"

#: ../server/importlib/userAuth.py:144
#, python-format
msgid ""
"You are not allowed to manage channel %s, or that channel does not exist"
msgstr ""
"Vous n'êtes pas autorisé à administrer le canal %s, ou ce canal n'existe pas"

#: ../server/importlib/userAuth.py:204
#, fuzzy, python-format
msgid ""
"\n"
"               %s Account has been deactivated on this server.\n"
"               Please contact your Org administrator for more help."
msgstr ""
"\n"
"                   Le compte %s a été désactivé sur ce serveur.\n"
"                   Veuillez contacter votre administrateur d'organisation "
"pour plus d'assistance."

#: ../server/rhnHandler.py:62
msgid "Please run rhn_register as root on this client"
msgstr ""

#: ../server/rhnHandler.py:75
#, python-format
msgid "Service not enabled for system profile: \"%s\""
msgstr "Service désactivé pour le profil de système : \"%s\""

#: ../server/rhnPackage.py:49 ../server/rhnPackage.py:87
#: ../server/rhnPackage.py:107 ../server/rhnPackage.py:158
#, python-format
msgid "Invalid RPM package %s requested"
msgstr "Paquet RPM %s demandé invalide"

#: ../server/rhnPackage.py:112
msgid "Package not found"
msgstr "Paquet non trouvé"

#: ../server/rhnServer/server_class.py:97
#, python-format
msgid "Architecture `%s' is not supported"
msgstr "L'architecture `%s' n'est pas supportée"

#: ../server/rhnServer/server_token.py:78
#, python-format
msgid "Token `%s' has more than one base channel assigned"
msgstr "Le jeton `%s' a plus d'un canal de base assigné"

#: ../server/rhnServer/server_token.py:80
msgid "Conflicting base channels"
msgstr "Canaux de base conflictuels"

#: ../server/rhnServer/server_token.py:190
#, python-format
msgid "Failed to add server to group %s"
msgstr "Échec dans l'ajout du serveur au groupe %s"

#: ../server/rhnServer/server_token.py:503
#, python-format
msgid "Maximum usage count of %s reached"
msgstr "Limite d'utilisation maximale de %s atteinte"

#: ../server/rhnServer/server_token.py:744
msgid ""
"Stacking of re-registration tokens with different base entitlements is not "
"supported"
msgstr ""
"L'empilement de jetons de réenregistrement avec des droits de base "
"différents n'est pas supporté"

#: ../server/rhnServer/server_token.py:811
#, python-format
msgid "Could not find token '%s'"
msgstr "Jeton '%s' introuvable"

#. Cannot use activation keys from different orgs
#: ../server/rhnServer/server_token.py:843
msgid "Tokens from mismatching orgs"
msgstr "Jetons provenant d'organisation incompatibles"

#. Two tokens with different kickstart sessions
#: ../server/rhnServer/server_token.py:853
msgid "Kickstart session mismatch"
msgstr "Inadéquation de session kickstart"

#: ../server/rhnServer/server_token.py:877
msgid "Stacking of re-registration tokens is not supported"
msgstr "L'empilement de jetons de réenregistrement n'est pas supporté"

#: ../server/rhnUser.py:289 ../server/rhnUser.py:292
msgid "Invalid username/password combination"
msgstr "Combinaison utilisateur/mot de passe invalide"

#. nope, not reserved either
#: ../server/rhnUser.py:467
#, python-format
msgid "Username `%s' has not been reserved"
msgstr "Le nom d'utilisateur `%s' n'a pas été réservé"

#. New accounts have to specify an e-mail address
#: ../server/rhnUser.py:473
msgid "E-mail address not specified"
msgstr "Adresse courriel non spécifiée"

#: ../server/rhnUser.py:509
#, python-format
msgid "username should be at least %d characters"
msgstr "Le nom d'utilisateur doit comporter au moins %d caractères"

#: ../server/rhnUser.py:512
#, python-format
msgid "username should be less than %d characters"
msgstr "Le nom d'utilisateur doit comporter au plus %d caractères"

#: ../server/rhnUser.py:523
#, python-format
msgid "username = `%s', invalid character `%s'"
msgstr "nom d'utilisateur = `%s', caractère invalide `%s'"

#: ../server/rhnUser.py:542
#, python-format
msgid "Please limit your e-mail address to %s chars"
msgstr "Veuillez limiter votre adresse courriel à %s caractères"

#: ../server/rhnUser.py:623
#, python-format
msgid "password must be at least %d characters"
msgstr "Le mot de passe doit comporter au moins %d caractères"

#: ../server/rhnUser.py:626
#, python-format
msgid "Password must be shorter than %d characters"
msgstr "Le mot de passe doit comporter au plus %d caractères"

#: ../server/rhnUser.py:644
#, python-format
msgid "password contains character `%s'"
msgstr "le mot de passe contient le caractère `%s'"

#: ../server/rhnUser.py:651
#, python-format
msgid "username should be at least %d characters long"
msgstr "Le nom d'utilisateur doit comporter au moins %d caractères"

#: ../server/rhnUser.py:662
#, python-format
msgid "Cannot register usernames ending with %s"
msgstr "Impossible d'enregistrer un nom d'utilisateur se terminant par %s"

#: ../server/apacheRequest.py:59
#, python-format
msgid "Invalid request received (%s)."
msgstr "Réception de requête invalide (%s)"

#: ../server/apacheRequest.py:120
#, python-format
msgid ""
"IMPORTANT MESSAGE FOLLOWS:\n"
"%s"
msgstr ""
"UN MESSAGE IMPORTANT SUIT :\n"
"%s"

#: ../server/apacheRequest.py:149
#, python-format
msgid ""
"While running '%s': caught\n"
"%s : %s\n"
msgstr ""
"Lors de l'exécution de '%s': exception levée\n"
"%s : %s\n"

#: ../server/apacheRequest.py:606
#, python-format
msgid "Invalid URI %s"
msgstr "URI invalide %s"

#: ../server/rhnChannel.py:1992
#, python-format
msgid ""
"Your account does not have access to any channels matching "
"(release='%(release)s', arch='%(arch)s')%(www_activation)s"
msgstr ""
"Votre compte n'a pas accès à aucun canal correspondant à "
"(release='%(release)s', arch='%(arch)s')%(www_activation)s"

#: ../server/rhnChannel.py:2002
msgid ""
"\n"
"If you have a registration number, please register with it first at http://"
"www.redhat.com/apps/activate/ and then try again.\n"
"\n"
msgstr ""
"\n"
"Si vous avez un numéro d'installation, veuillez d'abord l'enregistrer à "
"http://www.redhat.com/apps/activate/ puis de réessayer.\n"
"\n"

#: ../server/rhnChannel.py:2012
#, python-format
msgid "Insufficient subscription permissions for release (%s, %s"
msgstr "Permissions de souscriptions insuffisantes pour la version (%s, %s"

#. Various messages that can be reused
#.
#. bretm 02/07/2007 -- when we have better old-client documentation, probably
#. will be safe to get rid of all this crap
#: ../server/rhnChannel.py:2276 ../server/rhnChannel.py:2287
#: ../server/rhnChannel.py:2302
msgid "System Registered but Inactive"
msgstr "Système Enregistré mais Inactif"

#: ../server/rhnChannel.py:2277
#, fuzzy, python-format
msgid ""
"\n"
"Invalid Architecture and OS release combination (%s, %s).\n"
"Your system has been registered, but will not receive updates\n"
"because it is not subscribed to a channel. If you have not yet\n"
"activated your product for service, please visit our website at:\n"
"\n"
"     http://www.redhat.com/apps/activate/\n"
"\n"
"...to activate your product."
msgstr ""
"\n"
"Combinaison d'architecture et de version de l'OS (%s, %s) invalide.\n"
"Votre système a été enregistré, mais ne recevra pas de\n"
"mises à jour car il n'est pas abonné à un canal de base. Si vous n'avez\n"
"pas encore activé votre produit pour le service, veuillez visiter notre site "
"web à :\n"
"  \n"
"     http://www.redhat.com/apps/activate/\n"
"\n"
"...pour activer votre produit."

#: ../server/rhnChannel.py:2288
#, python-format
msgid ""
"\n"
"Invalid Architecture and OS release combination (%s, %s).\n"
"Your system has been registered, but will not receive updates\n"
"because it could not be subscribed to a base channel.\n"
"Please contact your organization administrator for assistance.\n"
msgstr ""
"\n"
"Combinaison d'architecture et de version de l'OS (%s, %s) invalide.\n"
"Votre système a été enregistré, mais ne recevra pas de\n"
"mises à jour car il n'est pas abonné à un canal de base.\n"
"Contacter l'administrateur de votre organisation pour une assistance.\n"

#: ../server/rhnChannel.py:2295
#, python-format
msgid ""
"\n"
"  This system has been successfully registered, but is not yet entitled\n"
"  to service.  To entitle this system to service, login to the web site at:\n"
"\n"
"  %(entitlement_url)s\n"
msgstr ""
"\n"
"  Ce système a été inscrit avec succès, mais n'a aucun droit d'accès\n"
"  au service. Pour attribuer à ce système un droit d'accès au service,\n"
"  se connecter au site web à l'adresse suivante :\n"
"\n"
"  %(entitlement_url)s\n"

#: ../server/rhnChannel.py:2303
#, python-format
msgid ""
"\n"
"  This system has been successfully registered, but no service entitlements\n"
"  were available.  To entitle this system to service, login to the web site "
"at:\n"
"\n"
"  %(entitlement_url)s\n"
msgstr ""
"\n"
"  Ce système a été inscrit avec succès, mais aucun droit d'accès au service\n"
"  n'est disponible. Pour attribuer à ce système un droit d'accès au "
"service,\n"
"  se connecter au site web à l'adresse suivante :\n"
"\n"
"  %(entitlement_url)s\n"

#. 0-999: Red Hat client/client-like interaction errors:
#: ../common/rhnException.py:53
msgid "This does not appear to be a valid username."
msgstr "Ceci ne semble pas être un nom d'utilisateur invalide."

#: ../common/rhnException.py:54
msgid "Invalid username and password combination."
msgstr "Combinaison utilisateur et mot de passe invalide."

#: ../common/rhnException.py:55
msgid "This login is already taken, or the password is incorrect."
msgstr "Cet identifiant est déjà utilisé, ou le mot de passe est incorrect."

#: ../common/rhnException.py:56
msgid "Permission denied."
msgstr "Permission refusée."

#: ../common/rhnException.py:57
msgid "Object not found."
msgstr "Objet non trouvé."

#: ../common/rhnException.py:58
msgid "Invalid System Digital ID."
msgstr "Identifiant numérique de système invalide."

#: ../common/rhnException.py:59
msgid "Invalid System Credentials."
msgstr "Informations d'identification du système invalides."

#: ../common/rhnException.py:60
msgid "Could not retrieve user data from database."
msgstr "Données utilisateur non trouvées dans la base."

#: ../common/rhnException.py:61
msgid "Valid username required."
msgstr "Nom d'utilisateur valide requis."

#: ../common/rhnException.py:62
msgid "Valid password required."
msgstr "Mot de passe valide requis."

#: ../common/rhnException.py:63
msgid "Minimum username length violation."
msgstr "Violation de la limite minimale de longueur du nom d'utilisateur."

#: ../common/rhnException.py:64
msgid "Minimum password length violation."
msgstr "Violation de la limite minimale de longueur du mot de passe."

#: ../common/rhnException.py:65
msgid "The username contains invalid characters."
msgstr "Le nom d'utilisateur contient des caractères invalides."

#: ../common/rhnException.py:66
msgid "File not found."
msgstr "Fichier non trouvé."

#: ../common/rhnException.py:67
msgid "Architecture and OS version combination is not supported."
msgstr "Combinaison architecture et OS non supportée."

#: ../common/rhnException.py:68
msgid "Could not retrieve system data from database."
msgstr "Impossible de récupérer les données du système."

#: ../common/rhnException.py:69
msgid "Invalid arguments passed to function."
msgstr "Arguments invalides passés à la fonction."

#: ../common/rhnException.py:70
msgid "Unable to retrieve requested entry."
msgstr "Impossible de récupérer l'entrée demandée."

#: ../common/rhnException.py:71
msgid "Could not update database entry."
msgstr "Impossible de mettre à jour l'entrée de base de données."

#: ../common/rhnException.py:72
msgid "Unsupported server architecture."
msgstr "Architecture serveur non supportée."

#: ../common/rhnException.py:73
#, fuzzy, python-format
msgid ""
"\n"
"     The anonymous server functionality is no longer available.\n"
"\n"
"     Please re-register this system by running mgr_register as root.\n"
"     Please visit https://%(hostname)s/rhn/systems/SystemEntitlements.do\n"
"     or login at https://%(hostname)s, and from the \"Overview\" tab,\n"
"     select \"Subscription Management\" to enable the service for this "
"system.\n"
"     "
msgstr ""
"\n"
"     La fonctionnalité serveur anonyme n'est plus disponible.\n"
"\n"
"     Veuillez réinscrire ce système en utilisant rhn_register\n"
"     (ou up2date --register sur Red Hat Enterprise Linux 3+) en tant que "
"root.\n"
"     Veuillez consulter https://%(hostname)s/rhn/systems/SystemEntitlements."
"do\n"
"     ou vous connecter sur https://%(hostname)s, et depuis l'onglet Aperçu,\n"
"     sélectionner « Gestion des Abonnements » pour activer le service RHN "
"sur\n"
"     ce système.\n"
"     "

#: ../common/rhnException.py:81
msgid "Record not available in the database."
msgstr "Enregistrement non disponible dans la base de données."

#: ../common/rhnException.py:82
msgid "Invalid value for entry."
msgstr "Valeur invalide pour l'entrée."

#: ../common/rhnException.py:83
#, fuzzy, python-format
msgid ""
"\n"
"     This system does not have a valid entitlement for SUSE Manager.\n"
"     Please visit https://%(hostname)s/rhn/systems/SystemEntitlements.do\n"
"     or login at https://%(hostname)s, and from the \"Overview\" tab,\n"
"     select \"Subscription Management\" to enable the service for this "
"system.\n"
"     "
msgstr ""
"\n"
"     Ce système n'a pas de droit valide pour accéder à Red Hat Network.\n"
"     Veuillez consulter https://%(hostname)s/rhn/systems/SystemEntitlements."
"do\n"
"     ou vous connecter sur https://%(hostname)s, et depuis l'onglet Aperçu,\n"
"     sélectionner « Gestion des Abonnements » pour activer le service RHN "
"sur\n"
"     ce système.\n"
"     "

#: ../common/rhnException.py:89
msgid "Channel error"
msgstr "Erreur de canal"

#: ../common/rhnException.py:90
msgid "Client session token is invalid."
msgstr "Le jeton de session cliente est invalide."

#: ../common/rhnException.py:91
msgid "Client session token has expired."
msgstr "Le jeton de session cliente a expiré."

#: ../common/rhnException.py:92
msgid "You are not authorized to retrieve the requested object."
msgstr "Vous n'êtes pas autorisé à récupérer l'objet demandé."

#: ../common/rhnException.py:93
msgid "Invalid action"
msgstr "Action invalide"

#: ../common/rhnException.py:94
msgid "You are not allowed to perform administrative tasks on this system."
msgstr ""
"Vous n'êtes pas autorisé à réaliser les tâches d'administration sur ce "
"système."

#: ../common/rhnException.py:96
msgid "The system is already subscribed to the specified channel."
msgstr "Ce système est déjà abonné au canal spécifié."

#: ../common/rhnException.py:97
msgid "The system is not currently subscribed to the specified channel."
msgstr "Ce système n'est pas abonné au canal spécifié."

#: ../common/rhnException.py:98
msgid "The specified channel does not exist."
msgstr "Le canal spécifié n'existe pas."

#: ../common/rhnException.py:99
msgid "Invalid channel version."
msgstr "Version de canal invalide."

#: ../common/rhnException.py:100
#, fuzzy
msgid ""
"\n"
"     User group membership limits exceeded.\n"
"\n"
"     The current settings for your account do not allow you to add another\n"
"     user account. Please check with the organization administrator for "
"your\n"
"     account if the maximum number of users allowed to subscribe to server "
"needs\n"
"     to be changed.\n"
"     "
msgstr ""
"\n"
"     Dépassement de la limite d'adhésion à des groupes d'utilisateur.\n"
"\n"
"     Les réglages actuels de votre compte ne vous autorisent pas à créer\n"
"     un compte utilisateur. Veuillez vérifier avec l'administrateur de "
"votre\n"
"     organisation de votre compte si le nombre maximal d'utilisateurs "
"autorisés\n"
"     à se connecter à RHN doit être modifié.\n"
"     "

#: ../common/rhnException.py:108
#, fuzzy
msgid ""
"\n"
"     System group membership limits exceeded.\n"
"\n"
"     The current settings for your account do not allow you to add another\n"
"     system profile. Please check with the organization administrator for "
"your\n"
"     account for modifying the maximum number of system profiles that can "
"be\n"
"     subscribed to your account.\n"
"     "
msgstr ""
"\n"
"     Dépassement de la limite d'adhésion à des groupes de systèmes.\n"
"\n"
"     Les réglages actuels de votre compte ne vous autorisent pas à créer\n"
"     un nouveau profil de système. Veuillez vérifier avec l'administrateur\n"
"     de votre organisation de votre compte si le nombre maximal de systèmes\n"
"     autorisés à s'inscrire sur RHN doit être modifié.\n"
"     "

#: ../common/rhnException.py:116
#, fuzzy
msgid ""
"\n"
"     Invalid architecture.\n"
"\n"
"     The architecture of the package is not supported by\n"
"     "
msgstr ""
"\n"
"     Architecture invalide.\n"
"\n"
"     L'architecture de ce paquet n'est pas prise en charge par Red Hat "
"Network\n"
"     "

#: ../common/rhnException.py:121
msgid "Invalid RPM header"
msgstr "En-tête RPM invalide"

#: ../common/rhnException.py:122
msgid ""
"\n"
"    This system is already registered as a Salt Minion. If you want to "
"register it as a traditional client\n"
"    please delete it first via the web UI or API and then register it using "
"the traditional tools.\n"
"    "
msgstr ""

#. For the uploading tools
#: ../common/rhnException.py:127
msgid "Invalid information uploaded to the server"
msgstr "Information invalide transmise au serveur"

#: ../common/rhnException.py:128
msgid "Error uploading network interfaces configuration."
msgstr "Erreur lors de l'envoi de la configuration des interfaces réseau."

#: ../common/rhnException.py:129
msgid ""
"\n"
"     Package Upload Failed due to uniqueness constraint violation.\n"
"     Make sure the package does not have any duplicate dependencies or\n"
"     does not already exists on the server\n"
"     "
msgstr ""
"\n"
"     Le transfert de paquet a échoué du fait de la violation de la\n"
"     contrainte d'unicité. Assurez-vous que le paquet ne possède pas\n"
"     de dépendance dupliquée ou n'existe pas déjà sur le serveur.\n"
"     "

#: ../common/rhnException.py:134
#, fuzzy
msgid ""
"\n"
"     The --force rhnpush option is disabled on this server.\n"
"     Please contact your SUSE Manager administrator for more help.\n"
"     "
msgstr ""
"\n"
"     L'option --force de rhnpush est désactivée sur ce serveur.\n"
"     Veuillez contacter votre administrateur de Satellite pour\n"
"     obtenir de l'aide.\n"
"     "

#. 60-70: token errors
#: ../common/rhnException.py:140
msgid ""
"\n"
"     The activation token specified could not be found on the server.\n"
"     Please retry with a valid key.\n"
"     "
msgstr ""
"\n"
"     La clé d'activation spécifiée est introuvable sur le serveur.\n"
"     Retenter avec une clé valide.\n"
"     "

#: ../common/rhnException.py:144
msgid "Too many systems registered using this registration token"
msgstr "Trop de systèmes enregistrés avec ce jeton d'enregistrement."

#: ../common/rhnException.py:145
msgid "Token contains invalid, obsoleted or insufficient settings"
msgstr ""
"Le jeton contient des configurations invalides, obsolètes ou insuffisantes."

#: ../common/rhnException.py:146
msgid "Conflicting activation tokens"
msgstr "Jetons d'activation en conflit"

#. 70-80: channel subscription errors
#: ../common/rhnException.py:149
msgid ""
"\n"
"     No matching base channel found for your system.\n"
"     "
msgstr ""

#: ../common/rhnException.py:152
msgid ""
"\n"
"     You do not have subscription permission to the designated channel.\n"
"     Please refer to your organization's channel or organization\n"
"     administrators for further details.\n"
"     "
msgstr ""
"\n"
"     Vous n'avez pas d'abonnement autorisant l'accès au canal désigné.\n"
"     Veuillez consulter vos administrateurs de canaux ou d'organisation\n"
"     pour plus de détails.\n"
"     "

#: ../common/rhnException.py:157
msgid "You can not unsubscribe from base channel."
msgstr "Vous ne pouvez pas vous désabonner du canal de base."

#: ../common/rhnException.py:158
msgid "SUSE Manager or Proxy channel can not be subscribed."
msgstr ""

#. 80-90: server group errors
#: ../common/rhnException.py:161
msgid "There was an error while trying to join the system to its groups"
msgstr ""
"Une erreur est survenue en essayant de faire adhérer le système à ses groupes"

#. 90-100: entitlement errors
#: ../common/rhnException.py:164
msgid "Unable to entitle system"
msgstr "Impossible d'accorder des droits au système"

#. 100-109: e-mail and uuid related faults
#: ../common/rhnException.py:167
msgid "Maximum e-mail length violation."
msgstr "Limite de taille de courriel dépassée."

#: ../common/rhnException.py:168
msgid "This system has been previously registered."
msgstr "Ce système est déjà enregistré."

#: ../common/rhnException.py:169
msgid "Invalid username"
msgstr "Nom d'utilisateur invalide"

#. 140-159 applet errors
#: ../common/rhnException.py:172
msgid "Unable to look up server"
msgstr "Impossible de rechercher le serveur"

#. 160-179: OSAD errors
#: ../common/rhnException.py:175
msgid "Required argument is missing"
msgstr "Un paramètre indispensable est manquant"

#. 600-699: RHEL5+ EN errors
#: ../common/rhnException.py:178
msgid "No entitlement information tied to hardware"
msgstr "Aucune information de droit n'est liée au matériel"

#: ../common/rhnException.py:179
msgid "Installation number is not entitling"
msgstr "Le numéro d'installation n'ouvre aucun droit"

#. 700-799: Additional user input verification errors.
#: ../common/rhnException.py:182
msgid "Maximum username length violation"
msgstr "Violation de la limite maximale de longueur du nom d'utilisateur"

#: ../common/rhnException.py:183
msgid "Maximum password length violation"
msgstr "Violation de la limite minimale de longueur du mot de passe"

#: ../common/rhnException.py:184
msgid "This user has read only API access. Action denied."
msgstr ""

#: ../common/rhnException.py:186
#, fuzzy
msgid "System Name cannot be less than 1 character"
msgstr "Le nom d'utilisateur doit comporter au plus %d caractères"

#. 1000-1999: Proxy specific errors:
#. issued by a Proxy to the client
#: ../common/rhnException.py:190
#, fuzzy
msgid "SUSE Manager Proxy error."
msgstr "Erreur de RHN Proxy."

#: ../common/rhnException.py:191
#, fuzzy
msgid "SUSE Manager Proxy unable to login."
msgstr "Le Proxy RHN est incapable de se connecter."

#. issued by a SUSE Manager Server/Satellite to the proxy
#: ../common/rhnException.py:193
msgid ""
"\n"
"     SUSE Manager Proxy system ID does not match a Spacewalk Proxy Server\n"
"     in the database.\n"
"     "
msgstr ""

#: ../common/rhnException.py:197
#, fuzzy
msgid "SUSE Manager Proxy session token is invalid."
msgstr "Le jeton de session du Proxy RHN est invalide."

#: ../common/rhnException.py:198
#, fuzzy
msgid "SUSE Manager Proxy session token has expired."
msgstr "Le jeton de session du Proxy RHN a expiré."

#. 2000-2999: Red Hat Satellite specific errors:
#: ../common/rhnException.py:202
#, fuzzy
msgid ""
"\n"
"      user creation is not allowed via mgr_register;\n"
"     please contact your sysadmin to have your account created.\n"
"     "
msgstr ""
"\n"
"     La création d'un utilisateur sur RHN Satellite n'est pas autorisée\n"
"     via rhn_register (ou up2date --register sur Red Hat\n"
"     Enterprise Linux 3 ou plus) ; veuillez contacter votre      "
"administrateur système afin qu'il puisse créer votre\n"
"     compte utilisateur.\n"
"     "

#: ../common/rhnException.py:206
#, fuzzy
msgid ""
"\n"
"     This SUSE Manager server is not allowed to use Inter Server Sync on "
"this server\n"
"     "
msgstr ""
"\n"
"     Ce serveur satellite n'est pas autorisé à utiliser la synchronisation "
"inter-satellite\n"
"     "

#: ../common/rhnException.py:209
#, fuzzy
msgid ""
"\n"
"     Inter Server Sync is disabled on this SUSE Manager Server.\n"
"     "
msgstr ""
"\n"
"     La synchronisation inter-satellite est désactivée sur ce satellite.\n"
"     "

#. 3000-3999: XML dumper errors:
#: ../common/rhnException.py:214
msgid "Invalid datatype passed"
msgstr "Type de données invalide passé"

#: ../common/rhnException.py:215
msgid "Unable to retrieve channel"
msgstr "Impossible de récupérer le canal"

#: ../common/rhnException.py:216
msgid "Unable to retrieve package"
msgstr "Impossible de récupérer le paquet"

#: ../common/rhnException.py:217
msgid "Unable to retrieve erratum"
msgstr "Impossible de récupérer l'erratum"

#: ../common/rhnException.py:218
msgid "File is missing"
msgstr "Le fichier est manquant"

#: ../common/rhnException.py:219
msgid "Function retrieval error"
msgstr "Erreur de récupération de la fonction"

#: ../common/rhnException.py:220
msgid "Function execution error"
msgstr "Erreur d'exécution de la fonction"

#: ../common/rhnException.py:221
msgid "Missing version string"
msgstr "Chaîne de version manquante"

#: ../common/rhnException.py:222
msgid "Invalid version string"
msgstr "Chaîne de version invalide"

#: ../common/rhnException.py:223
msgid "Mismatching versions"
msgstr "Versions incompatibles"

#: ../common/rhnException.py:224
msgid "Invalid channel version"
msgstr "Version de canal incompatible"

#: ../common/rhnException.py:225
msgid "No comps file for channel"
msgstr "Pas de fichier comps pour le canal"

#: ../common/rhnException.py:226
msgid "Unable to retrieve comps file"
msgstr "Impossible de récupérer le fichier comps"

#. 4000 - 4999: config management errors
#: ../common/rhnException.py:229
msgid "Configuration action missing"
msgstr "Action de configuration manquante"

#: ../common/rhnException.py:230
msgid "File too large"
msgstr "Fichier trop grand"

#: ../common/rhnException.py:231
msgid "File contains binary data"
msgstr "Le fichier contient des données binaires"

#: ../common/rhnException.py:232
msgid "Configuration channel is not empty"
msgstr "Le canal de configuration n'est pas vide"

#: ../common/rhnException.py:233
msgid "Permission error"
msgstr "Erreur d'autorisation"

#: ../common/rhnException.py:234
msgid "Content missing for configuration file"
msgstr "Contenu du fichier de configuration absent"

#: ../common/rhnException.py:235
msgid "Template delimiters not specified"
msgstr "Délimiteurs de macro non spécifié"

#: ../common/rhnException.py:236
msgid "Configuration channel does not exist"
msgstr "Le canal de configuration n'existe pas"

#: ../common/rhnException.py:237
msgid "Configuration channel already exists"
msgstr "Le canal de configuration existe déjà"

#: ../common/rhnException.py:238
msgid "File missing from configuration channel"
msgstr "Fichier absent du canal de configuration"

#: ../common/rhnException.py:239
msgid "Different revision of this file is uploaded"
msgstr "Une révision différente de ce fichier a déjà été transmise"

#: ../common/rhnException.py:240
msgid "File already uploaded to configuration channel"
msgstr "Ce fichier a déjà été transmis à ce canal de configuration"

#: ../common/rhnException.py:241
msgid "File size exceeds remaining quota space"
msgstr "La taille du fichier excède le quota restant"

#: ../common/rhnException.py:242
msgid "Full path of file must be specified"
msgstr "Le chemin complet du fichier doit être indiqué"

#: ../common/rhnException.py:243
msgid "Invalid revision number"
msgstr "Numéro de révision invalide"

#: ../common/rhnException.py:244
msgid "Cannot compare files of different file type"
msgstr "Impossible de comparer des fichiers de types différents"

#. 5000 - 5999: client content uploading errors
#. 5000 - 5099: crash reporting errors
#: ../common/rhnException.py:248
msgid "Crash information is invalid or incomplete"
msgstr ""

#: ../common/rhnException.py:249
msgid "Crash file information is invalid or incomplete"
msgstr ""

#: ../common/rhnException.py:250
msgid "Error composing crash directory path"
msgstr ""

#: ../common/rhnException.py:251
msgid "Error composing crash file path"
msgstr ""

#: ../common/rhnException.py:252 ../common/rhnException.py:259
#, fuzzy
msgid "Invalid content encoding"
msgstr "Code item invalide"

#: ../common/rhnException.py:253
#, fuzzy
msgid "Invalid crash name"
msgstr "Nom de paquetage invalide"

#: ../common/rhnException.py:254
msgid "Crash reporting is disabled for this organization"
msgstr ""

#. 5100 - 5199: scap results reporting error
#: ../common/rhnException.py:256
msgid "SCAP results file transfer is invalid or incomplete"
msgstr ""

#: ../common/rhnException.py:257
msgid "Error composing directory path for detailed SCAP results"
msgstr ""

#: ../common/rhnException.py:258
msgid "Error composing file path for detailed SCAP results"
msgstr ""

#: ../common/rhnException.py:306
#, fuzzy
msgid ""
"\n"
"     An error has occurred while processing your request. If this problem\n"
"     persists please enter a bug report at scc.suse.com.\n"
"     If you choose to submit the bug report, please be sure to include\n"
"     details of what you were trying to do when this error occurred and\n"
"     details on how to reproduce this problem.\n"
msgstr ""
"\n"
"     Une erreur est survenue pendant le traitement de votre demande. Si\n"
"     le problème persiste, merci de créer un rapport d'anomalie sur\n"
"     bugzilla.redhat.com. Si vous choisissez de soumettre ce rapport\n"
"     d'anomalie, assurez-vous d'y adjoindre les détails de ce que vous "
"étiez\n"
"     en train de faire lorsque l'erreur est survenue, ainsi que les détails\n"
"     sur la façon de reproduire le problème.\n"

#: ../common/rhnException.py:358
#, python-format
msgid ""
"Error Message:\n"
"    %s\n"
msgstr ""
"Message d'erreur :\n"
"    %s\n"

#: ../common/rhnException.py:360
#, python-format
msgid "Error Class Code: %s\n"
msgstr "Code de classe d'erreur : %s\n"

#: ../common/rhnException.py:363
#, python-format
msgid "Error Class Info: %s\n"
msgstr "Information de classe d'erreur : %s\n"

#: ../common/rhnException.py:365
#, python-format
msgid "Explanation: %s"
msgstr "Explication : %s"

#: ../common/rhnTB.py:205
#, python-format
msgid "ERROR: %s %s: %s"
msgstr ""

#: ../common/rhnTB.py:207
#, python-format
msgid "TRACEBACK: %s"
msgstr ""
